name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is and what you expected to happen
      placeholder: |
        **What happened:** Describe the bug
        **What you expected:** Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure terraform.tfvars with bucket_name = "my-example-bucket"
        2. Run 'terraform init'
        3. Run 'terraform plan'
        4. See error...
    validations:
      required: true

  - type: textarea
    id: terraform_output
    attributes:
      label: 🔍 Terraform Output & Configuration
      description: Include relevant Terraform command output and your configuration (remove sensitive data)
      placeholder: |
        **Terraform Output:**
        ```
        Paste your Terraform output here
        ```
        
        **Configuration:**
        ```hcl
        bucket_name = "my-terraform-state"
        aws_region = "us-east-1"
        dynamodb_table_name = "terraform-locks"
        ```
        
        **Additional Context:** Any other relevant information
      render: shell
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: 🔧 Environment
      description: Your Terraform version, AWS provider version, and AWS region
      placeholder: "Terraform: 1.6.0, AWS Provider: 5.100.0, Region: us-east-1"
    validations:
      required: true

  - type: dropdown
    id: operating_system
    attributes:
      label: 💻 Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Windows
        - Linux (Ubuntu)
        - Linux (CentOS/RHEL)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: ✅ Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included steps to reproduce and relevant output/configuration
          required: true
        - label: I have removed any sensitive information from my examples
          required: true 